version: '3.1'

services: 
    db:
        container_name: dev_db
        image: postgres:9.6.6
        restart: always
        volumes:
            - ../pgdb/:/var/lib/postgresql/data
        ports:
            - "5435:5432"
        env_file: ../.env

    adminer:
        image: adminer
        restart: always
        ports:
        - 8080:8080